2025-02-24 16:16:35,834 - ERROR - Connection to remote host was lost. - goodbye
2025-02-24 16:16:37,838 - ERROR - L\u1ed7i trong on_message_generic: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 36, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 71, in on_message_generic
    data = json.loads(message)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-02-24 16:16:40,876 - ERROR - L\u1ed7i trong on_message_generic: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 36, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 71, in on_message_generic
    data = json.loads(message)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-02-24 16:16:41,888 - ERROR - L\u1ed7i trong on_message_generic: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 36, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 71, in on_message_generic
    data = json.loads(message)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-02-24 16:16:42,899 - ERROR - L\u1ed7i trong on_message_generic: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 36, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 71, in on_message_generic
    data = json.loads(message)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-02-24 16:16:43,901 - ERROR - L\u1ed7i trong on_message_generic: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 36, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 71, in on_message_generic
    data = json.loads(message)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-02-24 16:16:44,911 - ERROR - L\u1ed7i trong on_message_generic: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 36, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 71, in on_message_generic
    data = json.loads(message)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-02-24 16:16:45,928 - ERROR - L\u1ed7i trong on_message_generic: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 36, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 71, in on_message_generic
    data = json.loads(message)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-02-24 16:16:46,941 - ERROR - L\u1ed7i trong on_message_generic: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 36, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 71, in on_message_generic
    data = json.loads(message)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-02-24 16:16:47,945 - ERROR - L\u1ed7i trong on_message_generic: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 36, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 71, in on_message_generic
    data = json.loads(message)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-02-24 16:16:48,969 - ERROR - L\u1ed7i trong on_message_generic: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 36, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 71, in on_message_generic
    data = json.loads(message)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-02-24 16:16:49,974 - ERROR - L\u1ed7i trong on_message_generic: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 36, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 71, in on_message_generic
    data = json.loads(message)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-02-24 16:17:35,624 - ERROR - Connection to remote host was lost. - goodbye
2025-02-24 16:17:35,807 - ERROR - Connection to remote host was lost. - goodbye
2025-02-24 16:18:37,079 - ERROR - L\u1ed7i trong on_message_generic: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 36, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 71, in on_message_generic
    data = json.loads(message)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-02-24 16:18:39,112 - ERROR - L\u1ed7i trong on_message_generic: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 36, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 71, in on_message_generic
    data = json.loads(message)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-02-24 16:18:40,118 - ERROR - L\u1ed7i trong on_message_generic: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 36, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 71, in on_message_generic
    data = json.loads(message)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-02-24 16:18:41,134 - ERROR - L\u1ed7i trong on_message_generic: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 36, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 71, in on_message_generic
    data = json.loads(message)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-02-24 16:18:42,155 - ERROR - L\u1ed7i trong on_message_generic: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 36, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 71, in on_message_generic
    data = json.loads(message)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-02-24 16:18:43,178 - ERROR - L\u1ed7i trong on_message_generic: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 36, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 71, in on_message_generic
    data = json.loads(message)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-02-24 16:18:44,192 - ERROR - L\u1ed7i trong on_message_generic: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 36, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 71, in on_message_generic
    data = json.loads(message)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-02-24 16:18:45,202 - ERROR - L\u1ed7i trong on_message_generic: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 36, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 71, in on_message_generic
    data = json.loads(message)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-02-24 16:18:46,212 - ERROR - L\u1ed7i trong on_message_generic: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 36, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 71, in on_message_generic
    data = json.loads(message)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-02-24 16:18:47,213 - ERROR - L\u1ed7i trong on_message_generic: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 36, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 71, in on_message_generic
    data = json.loads(message)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-02-24 16:18:48,217 - ERROR - L\u1ed7i trong on_message_generic: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 36, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 71, in on_message_generic
    data = json.loads(message)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-02-24 16:19:24,160 - ERROR - L\u1ed7i trong on_message_generic: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 38, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 73, in on_message_generic
    data = json.loads(message)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-02-24 16:19:26,179 - ERROR - L\u1ed7i trong on_message_generic: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 38, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 73, in on_message_generic
    data = json.loads(message)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-02-24 16:19:27,202 - ERROR - L\u1ed7i trong on_message_generic: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 38, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 73, in on_message_generic
    data = json.loads(message)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-02-24 16:19:28,237 - ERROR - L\u1ed7i trong on_message_generic: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 38, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 73, in on_message_generic
    data = json.loads(message)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-02-24 16:19:29,255 - ERROR - L\u1ed7i trong on_message_generic: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 38, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 73, in on_message_generic
    data = json.loads(message)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-02-24 16:19:30,270 - ERROR - L\u1ed7i trong on_message_generic: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 38, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 73, in on_message_generic
    data = json.loads(message)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-02-24 16:19:31,286 - ERROR - L\u1ed7i trong on_message_generic: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 38, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 73, in on_message_generic
    data = json.loads(message)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-02-24 16:19:32,308 - ERROR - L\u1ed7i trong on_message_generic: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 38, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 73, in on_message_generic
    data = json.loads(message)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-02-24 16:19:33,324 - ERROR - L\u1ed7i trong on_message_generic: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 38, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 73, in on_message_generic
    data = json.loads(message)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-02-24 16:19:34,332 - ERROR - L\u1ed7i trong on_message_generic: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 38, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 73, in on_message_generic
    data = json.loads(message)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-02-24 16:19:35,346 - ERROR - L\u1ed7i trong on_message_generic: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 38, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 73, in on_message_generic
    data = json.loads(message)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-02-24 16:20:20,447 - ERROR - Connection to remote host was lost. - goodbye
2025-02-24 16:20:20,612 - ERROR - Connection to remote host was lost. - goodbye
2025-02-24 16:20:34,016 - ERROR - L\u1ed7i trong on_message_generic: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 38, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 75, in on_message_generic
    message = message.decode('utf-8')
              ^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-02-24 16:20:37,060 - ERROR - L\u1ed7i trong on_message_generic: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 38, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 75, in on_message_generic
    message = message.decode('utf-8')
              ^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-02-24 16:20:38,075 - ERROR - L\u1ed7i trong on_message_generic: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 38, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 75, in on_message_generic
    message = message.decode('utf-8')
              ^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-02-24 16:20:39,091 - ERROR - L\u1ed7i trong on_message_generic: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 38, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 75, in on_message_generic
    message = message.decode('utf-8')
              ^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-02-24 16:20:40,106 - ERROR - L\u1ed7i trong on_message_generic: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 38, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\HelloWorld\ChenhLechSpotFuture.py", line 75, in on_message_generic
    message = message.decode('utf-8')
              ^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-02-24 16:25:27,547 - ERROR - Connection to remote host was lost. - goodbye
2025-02-24 16:25:27,826 - ERROR - Connection to remote host was lost. - goodbye
